# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :testing do
    gradle(task: "test")
  end

  desc "Submit a new Build to Internal Testing"
  lane :internal do
      upload_to_play_store(
          track: "internal",
          aab: "app/build/outputs/bundle/release/SpringLauncher_${CI_COMMIT_TAG}-release.aab",
          release_status: "draft"
        )
  end

  desc "Deploy a new version to the Google Play"
  lane :production do
    upload_to_play_store(
        track: "production",
        aab: "app/build/outputs/bundle/release/SpringLauncher_${CI_COMMIT_TAG}-release.aab",
        release_status: "draft",
    )
  end
end
